[project]
name = "lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Matheos touma", email = "matheos.touma@net.usj.edu.lb" }
]
requires-python = ">=3.10"
dependencies = [
    "mlflow>=3.16.0",
    "pillow>=10.0.0",
    "scikit-learn>=1.7.2",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
]

[project.scripts]
lab = "lab:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cpu" }
torchvision = { index = "pytorch-cpu" }
